"""create_planeacion_pedagogica_table

Revision ID: 1ea7505db4e4
Revises: b7c2d4e91a6f
Create Date: 2026-05-27 14:32:46.893480

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ea7505db4e4"
down_revision: Union[str, Sequence[str], None] = "b7c2d4e91a6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "planeaciones_pedagogicas",
        sa.Column("proyecto_id", sa.UUID(), nullable=False),
        sa.Column("competencia_id", sa.UUID(), nullable=False),
        sa.Column("fase_id", sa.UUID(), nullable=True),
        sa.Column("actividad_id", sa.UUID(), nullable=True),
        sa.Column(
            "estado",
            postgresql.ENUM(
                "BORRADOR",
                "EN_REVISION",
                "COMPLETO",
                "BLOQUEADO",
                name="estado_bloque",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "datos_complementarios",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("fecha_generacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actividad_id"],
            ["actividades_proyecto.id"],
            name=op.f("fk_planeaciones_pedagogicas_actividad_id_actividades_proyecto"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["competencia_id"],
            ["competencias.id"],
            name=op.f("fk_planeaciones_pedagogicas_competencia_id_competencias"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fase_id"],
            ["fases_proyecto.id"],
            name=op.f("fk_planeaciones_pedagogicas_fase_id_fases_proyecto"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos_formativos.id"],
            name=op.f("fk_planeaciones_pedagogicas_proyecto_id_proyectos_formativos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_planeaciones_pedagogicas")),
        sa.UniqueConstraint(
            "proyecto_id", "competencia_id", name="uq_planeacion_proyecto_competencia"
        ),
    )
    op.create_index(
        "ix_planeaciones_pedagogicas_competencia_id",
        "planeaciones_pedagogicas",
        ["competencia_id"],
        unique=False,
    )
    op.create_index(
        "ix_planeaciones_pedagogicas_proyecto_id",
        "planeaciones_pedagogicas",
        ["proyecto_id"],
        unique=False,
    )
    op.create_table(
        "planeacion_conocimientos",
        sa.Column("planeacion_id", sa.UUID(), nullable=False),
        sa.Column("conocimiento_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conocimiento_id"],
            ["conocimientos.id"],
            name=op.f("fk_planeacion_conocimientos_conocimiento_id_conocimientos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["planeacion_id"],
            ["planeaciones_pedagogicas.id"],
            name=op.f(
                "fk_planeacion_conocimientos_planeacion_id_planeaciones_pedagogicas"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "planeacion_id", "conocimiento_id", name=op.f("pk_planeacion_conocimientos")
        ),
    )
    op.create_table(
        "planeacion_criterios",
        sa.Column("planeacion_id", sa.UUID(), nullable=False),
        sa.Column("criterio_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["criterio_id"],
            ["criterios_evaluacion.id"],
            name=op.f("fk_planeacion_criterios_criterio_id_criterios_evaluacion"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["planeacion_id"],
            ["planeaciones_pedagogicas.id"],
            name=op.f("fk_planeacion_criterios_planeacion_id_planeaciones_pedagogicas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "planeacion_id", "criterio_id", name=op.f("pk_planeacion_criterios")
        ),
    )
    op.create_table(
        "planeacion_resultados",
        sa.Column("planeacion_id", sa.UUID(), nullable=False),
        sa.Column("resultado_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["planeacion_id"],
            ["planeaciones_pedagogicas.id"],
            name=op.f(
                "fk_planeacion_resultados_planeacion_id_planeaciones_pedagogicas"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resultado_id"],
            ["resultados_aprendizaje.id"],
            name=op.f("fk_planeacion_resultados_resultado_id_resultados_aprendizaje"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "planeacion_id", "resultado_id", name=op.f("pk_planeacion_resultados")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("planeacion_resultados")
    op.drop_table("planeacion_criterios")
    op.drop_table("planeacion_conocimientos")
    op.drop_index(
        "ix_planeaciones_pedagogicas_proyecto_id", table_name="planeaciones_pedagogicas"
    )
    op.drop_index(
        "ix_planeaciones_pedagogicas_competencia_id",
        table_name="planeaciones_pedagogicas",
    )
    op.drop_table("planeaciones_pedagogicas")
    # ### end Alembic commands ###
