"""create phase 1 base schema

Revision ID: 61df9cc6b86d
Revises:
Create Date: 2026-04-25 08:33:02.789150

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61df9cc6b86d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "borradores_sesion",
        sa.Column("tipo_bloque", sa.String(length=50), nullable=False),
        sa.Column("referencia_id", sa.UUID(), nullable=False),
        sa.Column("paso_actual", sa.String(length=100), nullable=False),
        sa.Column(
            "payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "estado_borrador",
            sa.Enum(
                "BORRADOR", "EN_REVISION", "COMPLETO", "BLOQUEADO", name="estado_bloque"
            ),
            nullable=False,
        ),
        sa.Column(
            "ultima_edicion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "btrim(paso_actual) <> ''",
            name=op.f("ck_borradores_sesion_paso_actual_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(tipo_bloque) <> ''",
            name=op.f("ck_borradores_sesion_tipo_bloque_not_blank"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_borradores_sesion")),
    )
    op.create_index(
        "ix_borradores_sesion_tipo_bloque_referencia_id",
        "borradores_sesion",
        ["tipo_bloque", "referencia_id"],
        unique=False,
    )
    op.create_table(
        "eventos_auditoria",
        sa.Column("entidad", sa.String(length=100), nullable=False),
        sa.Column("entidad_id", sa.UUID(), nullable=False),
        sa.Column("accion", sa.String(length=100), nullable=False),
        sa.Column("detalle", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "fecha_evento",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "btrim(accion) <> ''", name=op.f("ck_eventos_auditoria_accion_not_blank")
        ),
        sa.CheckConstraint(
            "btrim(entidad) <> ''", name=op.f("ck_eventos_auditoria_entidad_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eventos_auditoria")),
    )
    op.create_table(
        "programas_formacion",
        sa.Column("codigo_programa", sa.String(length=100), nullable=False),
        sa.Column("nombre_programa", sa.Text(), nullable=False),
        sa.Column("version_programa", sa.String(length=100), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "BORRADOR", "EN_REVISION", "COMPLETO", "BLOQUEADO", name="estado_bloque"
            ),
            nullable=False,
        ),
        sa.Column(
            "fuente_cargue",
            sa.Enum("PDF_EXTRACCION", "MANUAL", "MIXTO", name="tipo_fuente_cargue"),
            nullable=False,
        ),
        sa.Column("observaciones_revision", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(codigo_programa) <> ''",
            name=op.f("ck_programas_formacion_codigo_programa_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(nombre_programa) <> ''",
            name=op.f("ck_programas_formacion_nombre_programa_not_blank"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programas_formacion")),
        sa.UniqueConstraint(
            "codigo_programa",
            "version_programa",
            name="uq_programas_formacion_codigo_version_programa",
        ),
    )
    op.create_index(
        op.f("ix_programas_formacion_codigo_programa"),
        "programas_formacion",
        ["codigo_programa"],
        unique=False,
    )
    op.create_table(
        "competencias",
        sa.Column("programa_id", sa.UUID(), nullable=False),
        sa.Column("codigo_competencia", sa.String(length=100), nullable=False),
        sa.Column("nombre_competencia", sa.Text(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "BORRADOR", "EN_REVISION", "COMPLETO", "BLOQUEADO", name="estado_bloque"
            ),
            nullable=False,
        ),
        sa.Column(
            "origen_campo",
            sa.Enum(
                "EXTRAIDO",
                "MANUAL",
                "CORREGIDO",
                "PENDIENTE",
                "VALIDADO",
                name="estado_campo",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(codigo_competencia) <> ''",
            name=op.f("ck_competencias_codigo_competencia_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(nombre_competencia) <> ''",
            name=op.f("ck_competencias_nombre_competencia_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["programa_id"],
            ["programas_formacion.id"],
            name=op.f("fk_competencias_programa_id_programas_formacion"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competencias")),
        sa.UniqueConstraint(
            "programa_id",
            "codigo_competencia",
            name="uq_competencias_programa_codigo_competencia",
        ),
    )
    op.create_table(
        "proyectos_formativos",
        sa.Column("programa_id", sa.UUID(), nullable=False),
        sa.Column("codigo_proyecto", sa.String(length=100), nullable=False),
        sa.Column("nombre_proyecto", sa.Text(), nullable=False),
        sa.Column("version_proyecto", sa.String(length=100), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "BORRADOR", "EN_REVISION", "COMPLETO", "BLOQUEADO", name="estado_bloque"
            ),
            nullable=False,
        ),
        sa.Column(
            "fuente_cargue",
            sa.Enum("PDF_EXTRACCION", "MANUAL", "MIXTO", name="tipo_fuente_cargue"),
            nullable=False,
        ),
        sa.Column("observaciones_revision", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(codigo_proyecto) <> ''",
            name=op.f("ck_proyectos_formativos_codigo_proyecto_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(nombre_proyecto) <> ''",
            name=op.f("ck_proyectos_formativos_nombre_proyecto_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(version_proyecto) <> ''",
            name=op.f("ck_proyectos_formativos_version_proyecto_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["programa_id"],
            ["programas_formacion.id"],
            name=op.f("fk_proyectos_formativos_programa_id_programas_formacion"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proyectos_formativos")),
    )
    op.create_index(
        "ix_proyectos_formativos_programa_id",
        "proyectos_formativos",
        ["programa_id"],
        unique=False,
    )
    op.create_table(
        "conocimientos",
        sa.Column("competencia_id", sa.UUID(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("SABER", "PROCESO", name="tipo_conocimiento"),
            nullable=False,
        ),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "EXTRAIDO",
                "MANUAL",
                "CORREGIDO",
                "PENDIENTE",
                "VALIDADO",
                name="estado_campo",
            ),
            nullable=False,
        ),
        sa.Column(
            "motivo_fallo_extraccion",
            sa.Enum(
                "PDF_ESCANEADO",
                "DOCUMENTO_ILEGIBLE",
                "BAJA_RESOLUCION",
                "ESTRUCTURA_NO_RECONOCIDA",
                "CAMPO_NO_ENCONTRADO",
                "CONTENIDO_AMBIGUO",
                "ARCHIVO_PROTEGIDO",
                name="motivo_fallo_extraccion",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(descripcion) <> ''",
            name=op.f("ck_conocimientos_descripcion_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["competencia_id"],
            ["competencias.id"],
            name=op.f("fk_conocimientos_competencia_id_competencias"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conocimientos")),
        sa.UniqueConstraint(
            "competencia_id",
            "tipo",
            "descripcion",
            name="uq_conocimientos_competencia_tipo_descripcion",
        ),
    )
    op.create_index(
        "ix_conocimientos_competencia_id_tipo",
        "conocimientos",
        ["competencia_id", "tipo"],
        unique=False,
    )
    op.create_table(
        "criterios_evaluacion",
        sa.Column("competencia_id", sa.UUID(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "EXTRAIDO",
                "MANUAL",
                "CORREGIDO",
                "PENDIENTE",
                "VALIDADO",
                name="estado_campo",
            ),
            nullable=False,
        ),
        sa.Column(
            "motivo_fallo_extraccion",
            sa.Enum(
                "PDF_ESCANEADO",
                "DOCUMENTO_ILEGIBLE",
                "BAJA_RESOLUCION",
                "ESTRUCTURA_NO_RECONOCIDA",
                "CAMPO_NO_ENCONTRADO",
                "CONTENIDO_AMBIGUO",
                "ARCHIVO_PROTEGIDO",
                name="motivo_fallo_extraccion",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(descripcion) <> ''",
            name=op.f("ck_criterios_evaluacion_descripcion_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["competencia_id"],
            ["competencias.id"],
            name=op.f("fk_criterios_evaluacion_competencia_id_competencias"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_criterios_evaluacion")),
        sa.UniqueConstraint(
            "competencia_id",
            "descripcion",
            name="uq_criterios_evaluacion_competencia_descripcion",
        ),
    )
    op.create_index(
        "ix_criterios_evaluacion_competencia_id",
        "criterios_evaluacion",
        ["competencia_id"],
        unique=False,
    )
    op.create_table(
        "fases_proyecto",
        sa.Column("proyecto_id", sa.UUID(), nullable=False),
        sa.Column("nombre_fase", sa.String(length=255), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "EXTRAIDO",
                "MANUAL",
                "CORREGIDO",
                "PENDIENTE",
                "VALIDADO",
                name="estado_campo",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(nombre_fase) <> ''",
            name=op.f("ck_fases_proyecto_nombre_fase_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos_formativos.id"],
            name=op.f("fk_fases_proyecto_proyecto_id_proyectos_formativos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fases_proyecto")),
    )
    op.create_index(
        "ix_fases_proyecto_proyecto_id", "fases_proyecto", ["proyecto_id"], unique=False
    )
    op.create_table(
        "resultados_aprendizaje",
        sa.Column("competencia_id", sa.UUID(), nullable=False),
        sa.Column("codigo_resultado", sa.String(length=100), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "EXTRAIDO",
                "MANUAL",
                "CORREGIDO",
                "PENDIENTE",
                "VALIDADO",
                name="estado_campo",
            ),
            nullable=False,
        ),
        sa.Column(
            "motivo_fallo_extraccion",
            sa.Enum(
                "PDF_ESCANEADO",
                "DOCUMENTO_ILEGIBLE",
                "BAJA_RESOLUCION",
                "ESTRUCTURA_NO_RECONOCIDA",
                "CAMPO_NO_ENCONTRADO",
                "CONTENIDO_AMBIGUO",
                "ARCHIVO_PROTEGIDO",
                name="motivo_fallo_extraccion",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(descripcion) <> ''",
            name=op.f("ck_resultados_aprendizaje_descripcion_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["competencia_id"],
            ["competencias.id"],
            name=op.f("fk_resultados_aprendizaje_competencia_id_competencias"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resultados_aprendizaje")),
        sa.UniqueConstraint(
            "competencia_id",
            "descripcion",
            name="uq_resultados_aprendizaje_competencia_descripcion",
        ),
    )
    op.create_index(
        "ix_resultados_aprendizaje_competencia_id",
        "resultados_aprendizaje",
        ["competencia_id"],
        unique=False,
    )
    op.create_table(
        "actividades_proyecto",
        sa.Column("fase_id", sa.UUID(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "EXTRAIDO",
                "MANUAL",
                "CORREGIDO",
                "PENDIENTE",
                "VALIDADO",
                name="estado_campo",
            ),
            nullable=False,
        ),
        sa.Column(
            "motivo_fallo_extraccion",
            sa.Enum(
                "PDF_ESCANEADO",
                "DOCUMENTO_ILEGIBLE",
                "BAJA_RESOLUCION",
                "ESTRUCTURA_NO_RECONOCIDA",
                "CAMPO_NO_ENCONTRADO",
                "CONTENIDO_AMBIGUO",
                "ARCHIVO_PROTEGIDO",
                name="motivo_fallo_extraccion",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(descripcion) <> ''",
            name=op.f("ck_actividades_proyecto_descripcion_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["fase_id"],
            ["fases_proyecto.id"],
            name=op.f("fk_actividades_proyecto_fase_id_fases_proyecto"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actividades_proyecto")),
        sa.UniqueConstraint(
            "fase_id", "descripcion", name="uq_actividades_proyecto_fase_descripcion"
        ),
    )
    op.create_index(
        "ix_actividades_proyecto_fase_id",
        "actividades_proyecto",
        ["fase_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_actividades_proyecto_fase_id", table_name="actividades_proyecto")
    op.drop_table("actividades_proyecto")
    op.drop_index(
        "ix_resultados_aprendizaje_competencia_id",
        table_name="resultados_aprendizaje",
    )
    op.drop_table("resultados_aprendizaje")
    op.drop_index("ix_fases_proyecto_proyecto_id", table_name="fases_proyecto")
    op.drop_table("fases_proyecto")
    op.drop_index(
        "ix_criterios_evaluacion_competencia_id",
        table_name="criterios_evaluacion",
    )
    op.drop_table("criterios_evaluacion")
    op.drop_index("ix_conocimientos_competencia_id_tipo", table_name="conocimientos")
    op.drop_table("conocimientos")
    op.drop_index(
        "ix_proyectos_formativos_programa_id", table_name="proyectos_formativos"
    )
    op.drop_table("proyectos_formativos")
    op.drop_table("competencias")
    op.drop_index(
        op.f("ix_programas_formacion_codigo_programa"),
        table_name="programas_formacion",
    )
    op.drop_table("programas_formacion")
    op.drop_table("eventos_auditoria")
    op.drop_index(
        "ix_borradores_sesion_tipo_bloque_referencia_id",
        table_name="borradores_sesion",
    )
    op.drop_table("borradores_sesion")
    sa.Enum(name="motivo_fallo_extraccion").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="tipo_conocimiento").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="tipo_fuente_cargue").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="estado_campo").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="estado_bloque").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
