"""Add resultado_id to Conocimiento and CriterioEvaluacion

Revision ID: af3db3c40926
Revises: 2b4d9e7a1c23
Create Date: 2026-05-07 18:02:02.767556

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af3db3c40926"
down_revision: Union[str, Sequence[str], None] = "2b4d9e7a1c23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conocimientos", sa.Column("resultado_id", sa.UUID(), nullable=True))
    op.drop_constraint(
        op.f("uq_conocimientos_competencia_tipo_descripcion"),
        "conocimientos",
        type_="unique",
    )
    op.create_index(
        "uq_conocimientos_comp_tipo_desc_norap",
        "conocimientos",
        ["competencia_id", "tipo", "descripcion"],
        unique=True,
        postgresql_where=sa.text("resultado_id IS NULL"),
    )
    op.create_index(
        "uq_conocimientos_comp_tipo_desc_rap",
        "conocimientos",
        ["competencia_id", "tipo", "descripcion", "resultado_id"],
        unique=True,
        postgresql_where=sa.text("resultado_id IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_conocimientos_resultado_id_resultados_aprendizaje"),
        "conocimientos",
        "resultados_aprendizaje",
        ["resultado_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "criterios_evaluacion", sa.Column("resultado_id", sa.UUID(), nullable=True)
    )
    op.drop_constraint(
        op.f("uq_criterios_evaluacion_competencia_descripcion"),
        "criterios_evaluacion",
        type_="unique",
    )
    op.create_index(
        "uq_criterios_eval_comp_desc_norap",
        "criterios_evaluacion",
        ["competencia_id", "descripcion"],
        unique=True,
        postgresql_where=sa.text("resultado_id IS NULL"),
    )
    op.create_index(
        "uq_criterios_eval_comp_desc_rap",
        "criterios_evaluacion",
        ["competencia_id", "descripcion", "resultado_id"],
        unique=True,
        postgresql_where=sa.text("resultado_id IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_criterios_evaluacion_resultado_id_resultados_aprendizaje"),
        "criterios_evaluacion",
        "resultados_aprendizaje",
        ["resultado_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_criterios_evaluacion_resultado_id_resultados_aprendizaje"),
        "criterios_evaluacion",
        type_="foreignkey",
    )
    op.drop_index(
        "uq_criterios_eval_comp_desc_rap",
        table_name="criterios_evaluacion",
        postgresql_where=sa.text("resultado_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_criterios_eval_comp_desc_norap",
        table_name="criterios_evaluacion",
        postgresql_where=sa.text("resultado_id IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_criterios_evaluacion_competencia_descripcion"),
        "criterios_evaluacion",
        ["competencia_id", "descripcion"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("criterios_evaluacion", "resultado_id")
    op.drop_constraint(
        op.f("fk_conocimientos_resultado_id_resultados_aprendizaje"),
        "conocimientos",
        type_="foreignkey",
    )
    op.drop_index(
        "uq_conocimientos_comp_tipo_desc_rap",
        table_name="conocimientos",
        postgresql_where=sa.text("resultado_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_conocimientos_comp_tipo_desc_norap",
        table_name="conocimientos",
        postgresql_where=sa.text("resultado_id IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_conocimientos_competencia_tipo_descripcion"),
        "conocimientos",
        ["competencia_id", "tipo", "descripcion"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("conocimientos", "resultado_id")
    # ### end Alembic commands ###
